server:
  servlet:
    context-path: /meal_plan
  port: 8085
spring:
  application:
    name: Plans app
  datasource:
    url: jdbc:postgresql://localhost:5433/plans_test
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
recipes:
  service:
    url: http://localhost:8083/meal_plan